// ============================================================
// FIREBASE CONFIGURATION
// ============================================================
// WEEK 3: Replace the placeholder values below with YOUR
// Firebase project config from:
//   Firebase Console > Project Settings > Your Apps > Web App
//
// DO NOT edit this file until Week 3 (Deliverable 3).
// ============================================================

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {

  apiKey: "AIzaSyBQJYjrWKhaKeUv2-5X5HgCT1n3US9-VU8",

  authDomain: "ember-and-fig.firebaseapp.com",

  projectId: "ember-and-fig",

  storageBucket: "ember-and-fig.firebasestorage.app",

  messagingSenderId: "378440159514",

  appId: "1:378440159514:web:574ea3739e29eb1c809ca3"

};


// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firestore and export it
export const db = getFirestore(app);
